<?php

$title = 'New account';
$this->headTitle($title);

$form->setAttribute('action', $this->url('register'));
$form->get('submit')->setAttributes(['class'=>'btn btn-lg btn-primary btn-block']);
$form->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'name@example.com'
]);
$form->get('name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'John Doe'
]);
$form->get('pass')->setAttributes([
    'class'=>'form-control'
]);
$form->get('pass2')->setAttributes([
    'class'=>'form-control'
]);
$form->get('regkey')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'contact Arkhchance to get your key'
]);
$form->get('captcha')->setAttributes([
    'class'=>'form-control'
]);
$form->prepare();
?>



<div class="row justify-content-center">
    <div class="col-md-3">
        <h1><?= $this->escapehtml($title) ?> : </h1>
        <?= $this->form()->openTag($form); ?>
        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('pass')); ?>
            <?= $this->formElement($form->get('pass')); ?>
            <?= $this->formElementErrors($form->get('pass')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('pass2')); ?>
            <?= $this->formElement($form->get('pass2')); ?>
            <?= $this->formElementErrors($form->get('pass2')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('regkey')); ?>
            <?= $this->formElement($form->get('regkey')); ?>
            <?= $this->formElementErrors($form->get('regkey')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('captcha')); ?>
            <?= $this->formElement($form->get('captcha')); ?>
            <?= $this->formElementErrors($form->get('captcha')); ?>
        </div>
            <?= $this->formElement($form->get('submit')); ?>
            <?= $this->form()->closeTag(); ?>
    </div>
</div>
