<?php
$title = 'Reset your password';
$this->headTitle($title);
$form->get('submit')->setAttributes(['class'=>'btn btn-lg btn-primary btn-block']);
$form->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Email address'
    ]);
$form->get('captcha')->setAttributes([
    'class'=>'form-control'
    ]);
$form->prepare();
?>

<div class="row justify-content-md-center">
    <div class="col-md-3">
        <?= $this->form()->openTag($form); ?>

        <h2>Reset Password</h2>
        <?php if(isset($send) && $send): ?>
            <div class="alert alert-warning" role="alert">
                <p>Email send (check your spam folder)</p>
            </div>
    <?php else:  ?>
            <p>Enter your e-mail address below to reset your password</p>
        <?php endif;  ?>
            <div class="form-group">
                <?= $this->formElement($form->get('email')); ?>
                <?= $this->formElementErrors($form->get('email')); ?>
            </div>
            <div class="form-group">
                <?= $this->formElement($form->get('captcha')); ?>
                <p class="hint">Enter the letters above as you see them.</p>
                <?= $this->formElementErrors($form->get('captcha')); ?>
            </div>
        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
