<?php
$title = $this->escapeHtml($vulga->getNom());
$this->headTitle($title);
$this->headLink()->appendStylesheet($this->basePath('css/bootstrap-select.min.css'));
$this->headScript()->appendFile($this->basePath('js/bootstrap-select.min.js'));

$lastMS = $vulga->getMainstats()->last();

$note = "ex : enlever le domaine X, mettre Y à la place";
$form->get('submit')->setAttributes(['class'=>'btn btn-lg btn-primary btn-block']);
$form->get('note')->setAttributes([
    'class'=>'form-control',
    'placeholder' => $note,
    'rows' => 4
]);
$form->get('captcha')->setAttributes([
    'class'=>'form-control',
]);

?>
<style>
.fa-spin-hover:hover {
    -webkit-animation: fa-spin 2s infinite linear;
    -moz-animation: fa-spin 2s infinite linear;
    -o-animation: fa-spin 2s infinite linear;
    animation: fa-spin 2s infinite linear;
    cursor: pointer;
}
</style>
<div class="row m-1 justify-content-center">
    <div class="col-4 mt-5">
        <div class="row">
            <h1><?= $title; ?></h1>
        </div>
        <div class="row">
            <ul>
                <li>
                    <a target="_blank" rel="noopener noreferrer" href="<?= $lastMS->getLink(); ?>">
                        <?= $this->escapeHtml($lastMS->getLink()); ?>
                    </a>
                </li>
                <li>mis à jour le <?= date('j F Y à H:i:s',$lastMS->getDate()->getTimestamp()); ?></li>
                <li><?= $this->formatData()->format($lastMS->getFollower()); ?> abonnés</li>
                <li><?= $this->formatData()->format($lastMS->getPosts()); ?> vidéos</li>
                <li><?= $this->formatData()->format($lastMS->getTotalLike()); ?> likes</li>
                <li><?= $this->formatData()->format($lastMS->getTotalDislike()); ?> dislikes</li>
                <li><?= $this->formatData()->format($lastMS->getTotalVue()); ?> vues</li>
            </ul>
        </div>
        <div class="row">
            <p><?= $title ?> est dans les domaines suivant : </p>
        </div>
        <div class="row">
            <ul>
                <?php foreach ($vulga->getDomaine() as $domaine): ?>
                    <li><?= $domaine->getNom(); ?></li>
                <?php endforeach; ?>
            </ul>
        </div>
        <div class="row">
            <p><?= $title ?> est :</p>
        </div>
        <div class="row mb-5">
            <ul>
                <li>Considéré <?= $vulga->getSexeAsString(); ?></li>
                <li>Résidant en <?= $vulga->getPays()->getDrapeau(); ?></li>
                <li>Parlant principalement <?= $vulga->getLangue()->getDrapeau(); ?></li>
            </ul>
        </div>
        <div class="row mt-5" id="refresh">
            <p>Demandez une mise à jour : <i class="fa fa-refresh fa-spin-hover fa-fw"></i></p>
        </div>
        <div class="row">
            <p>Une erreur : Dites-le moi ! </p>
        </div>
        <div class="row">
            <?= $this->form()->openTag($form); ?>
            <div class="form-group">
                <?= $this->formElement($form->get('note')); ?>
            </div>
            <div class="form-group">
                <?= $this->formLabel($form->get('captcha')); ?>
                <?= $this->formElement($form->get('captcha')); ?>
                <?= $this->formElementErrors($form->get('captcha')); ?>
            </div>
            <?= $this->formElement($form->get('csrf')) ?>
            <?= $this->formElement($form->get('submit')); ?>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>
<?php
$this->inlineScript()->captureStart();
?>
$(document).ready(function () {
    <?php if(isset($success)): ?>
        alert("C'est envoyer ;)");
    <?php endif; ?>
    $(".fa").click(function(){
        $.ajax({
           type: 'GET',
           url: '/vulgarisateurs/refresh/<?= $vulga->getId(); ?>',
           success: function (data) {
                alert("C'est noté");
                $("#refresh").hide();
           }
       });
    });
});
<?php
$this->inlineScript()->captureEnd();
?>
