<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Science stats')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('Title','Science yt stats')
            ->appendName('Description','Des graphs et des stats sur les vulgarisateurs du web')
            ->setProperty('og:title', 'Science Stats')
            ->setProperty('og:type', 'website')
            ->setProperty('og:locale', 'fr_FR')
            ->setProperty('og:url', 'https://www.arkhchance.ovh')
            ->setProperty('og:image', 'https://www.arkhchance.ovh/img/stats.png')
            ->setProperty('og:description', 'Des graphs et des stats sur les vulgarisateurs du web')
            ->setProperty('og:image:alt', 'stats')
            ->setProperty('twitter:card', 'summary_large_image')
            ->setProperty('twitter:url', 'https://www.arkhchance.ovh')
            ->setProperty('twitter:image', 'https://www.arkhchance.ovh/img/stats.png')
            ->setProperty('twitter:description', 'Des graphs et des stats sur les vulgarisateurs du web')
            ->setProperty('twitter:title', 'Science Stats');
        ?>
        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/png', 'href' => $this->basePath('img/stats.png')])
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('css/main.css'))
                ->prependStylesheet($this->basePath('css/tingle.min.css'))
                ->prependStylesheet('https://cdn.jsdelivr.net/npm/fork-awesome@1.1.7/css/fork-awesome.min.css');
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/main.js'))
            ->prependFile($this->basePath('js/tingle.min.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/popper.min.js'))
        ?>
    </head>
    <body class="bgperso">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand" href="<?= $this->url('home') ?>"><img src="<?= $this->basePath('img/stats.png') ?>" height="28" alt="stats"/></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#contentcollapse" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <?= $this->mainMenu()->render(); ?>
        </nav>
        <div id="container-fluid">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2019 - <?= date('Y') ?> by Arkhchance.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
