<?php

$title = 'Domaine';
$this->headTitle($title);

$this->headLink()->appendStylesheet($this->basePath('css/manage.css'));

$form->get('submit')->setAttributes(['class'=>'btn btn-lg btn-primary btn-block']);

$form->get('domaine')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'quelle domaine ?'
]);
$form->get('desc')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'desc du domaine',
]);
$form->prepare();
?>
<div class="row justify-content-center">
    <h1 class="mt-4 mb-5">
        <?= $title; ?>
    </h1>
</div>
<div class="row justify-content-center">
    <div class="col-sm-3">
        <?= $this->formDisplay()->renderDomaine(); ?>
    </div>
    <div class="col-sm-3">
        <?= $this->form()->openTag($form); ?>
        <div class="form-group">
            <?= $this->formLabel($form->get('domaine')); ?>
            <?= $this->formElement($form->get('domaine')); ?>
            <?= $this->formElementErrors($form->get('domaine')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('desc')); ?>
            <?= $this->formElement($form->get('desc')); ?>
            <?= $this->formElementErrors($form->get('desc')); ?>
        </div>
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->formElement($form->get('csrf')) ?>
        <?= $this->form()->closeTag(); ?>
        <button id="delete" type="button" mode="domaine" class="btn mt-3 btn-danger btn-lg btn-block">del domaine(s)</button>
    </div>
</div>
<?php
$this->inlineScript()->appendFile($this->basePath('js/manage.js'));
 ?>
