<?php

$title = 'langues';
$this->headTitle($title);

$this->headLink()->appendStylesheet($this->basePath('css/manage.css'));

$form->get('submit')->setAttributes(['class'=>'btn btn-lg btn-primary btn-block']);

$form->get('langue')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'quelle langue ?'
]);
$form->get('code')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'code de la langue ex : "fr" "us"',
]);
$form->get('drapeau')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Drapeau ex : 🇫🇷',
]);
$form->prepare();
print_r($form->getMessages());
?>
<div class="row justify-content-center">
    <h1 class="mt-4 mb-5">
        <?= $title; ?>
    </h1>
</div>
<div class="row justify-content-center">
    <div class="col-sm-3">
        <?= $this->formDisplay()->renderLangue(); ?>
    </div>
    <div class="col-sm-3">
        <?= $this->form()->openTag($form); ?>
        <div class="form-group">
            <?= $this->formLabel($form->get('langue')); ?>
            <?= $this->formElement($form->get('langue')); ?>
            <?= $this->formElementErrors($form->get('langue')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('code')); ?>
            <?= $this->formElement($form->get('code')); ?>
            <?= $this->formElementErrors($form->get('code')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('drapeau')); ?>
            <?= $this->formElement($form->get('drapeau')); ?>
            <?= $this->formElementErrors($form->get('drapeau')); ?>
        </div>
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->formElement($form->get('csrf')) ?>
        <?= $this->form()->closeTag(); ?>
        <button id="delete" type="button" mode="langue" class="btn mt-3 btn-danger btn-lg btn-block">del langue(s)</button>
    </div>
</div>

<?php
$this->inlineScript()->appendFile($this->basePath('js/manage.js'));
 ?>
