<?php

$title = 'Lien';
$this->headTitle($title);

$this->headLink()->appendStylesheet($this->basePath('css/manage.css'));
$this->headLink()->appendStylesheet($this->basePath('css/bootstrap-select.min.css'));
$this->headScript()->appendFile($this->basePath('js/bootstrap-select.min.js'));

$form->get('submit')->setAttributes(['class'=>'btn btn-lg btn-primary btn-block']);


$form->get('vulga')->setAttributes(array(
    'class'=> 'selectpicker form-control',
    'data-live-search'  => 'true',
));
$form->get('pf')->setAttributes(array(
    'class'=> 'selectpicker form-control',
    'data-live-search'  => 'true',
));
$form->get('link')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'compte twitter ou chaine youtube',
]);
$form->prepare();
if(isset($error))
    echo $error;

?>
<div class="row justify-content-center">
    <h1 class="mt-4 mb-5">
        <?= $title; ?>
    </h1>
</div>
<div class="row justify-content-center">
    <div class="col-sm-8">
        <?= $this->formDisplay()->renderLink($page); ?>
        <?= $this->paginationControl($this->formDisplay()->pagiLink,'Sliding','science/partial/paginator',['route' => 'manage','action' => 'link']); ?>
    </div>
    <div class="col-sm-4">
        <?= $this->form()->openTag($form); ?>
        <div class="form-group">
            <?= $this->formLabel($form->get('vulga')); ?>
            <?= $this->formElement($form->get('vulga')); ?>
            <?= $this->formElementErrors($form->get('vulga')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('pf')); ?>
            <?= $this->formElement($form->get('pf')); ?>
            <?= $this->formElementErrors($form->get('pf')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('link')); ?>
            <?= $this->formElement($form->get('link')); ?>
            <?= $this->formElementErrors($form->get('link')); ?>
        </div>
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>
<?php
$this->inlineScript()->appendFile($this->basePath('js/manage.js'));
 ?>
