<?php

$title = 'Pays';
$this->headTitle($title);

$this->headLink()->appendStylesheet($this->basePath('css/manage.css'));

$form->get('submit')->setAttributes(['class'=>'btn btn-lg btn-primary btn-block']);

$form->get('pays')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'quelle pays ?'
]);
$form->get('code')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'code de la pays ex : "fr" "us"',
]);
$form->get('drapeau')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Drapeau ex : 🇫🇷',
]);
$form->prepare();
?>
<div class="row m-1 justify-content-center">
    <h1 class="mt-4 mb-5">
        <?= $title; ?>
    </h1>
</div>
<div class="row m-1 justify-content-center">
    <div class="col-sm-3">
        <?= $this->formDisplay()->renderPays(); ?>
    </div>
    <div class="col-sm-3">
        <?= $this->form()->openTag($form); ?>
        <div class="form-group">
            <?= $this->formLabel($form->get('pays')); ?>
            <?= $this->formElement($form->get('pays')); ?>
            <?= $this->formElementErrors($form->get('pays')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('code')); ?>
            <?= $this->formElement($form->get('code')); ?>
            <?= $this->formElementErrors($form->get('code')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('drapeau')); ?>
            <?= $this->formElement($form->get('drapeau')); ?>
            <?= $this->formElementErrors($form->get('drapeau')); ?>
        </div>
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
        <button id="delete" type="button" mode="pays" class="btn mt-3 btn-danger btn-lg btn-block">del pays(s)</button>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-sm-6">
        <p class="text-muted">
            <a target="_blank" rel="noopener noreferrer" href="https://apps.timwhitlock.info/emoji/tables/iso3166">Drapeau</a>
            <a target="_blank" rel="noopener noreferrer" href="http://documentation.abes.fr/sudoc/formats/CodesPays.htm">Code</a>
        </p>
    </div>
</div>
<?php
$this->inlineScript()->appendFile($this->basePath('js/manage.js'));
 ?>
