<?php
$this->headLink()->appendStylesheet($this->basePath('css/Chart.css'));
$this->headScript()->appendFile($this->basePath('js/Chart.bundle.min.js'));
function echoData($array,$key,$quote) {
    $data = "";
    $cpt = 0;
    foreach ($array as $value) {
        if($quote)
            $data .= "'".addslashes($value[$key])."',";
        else
            $data .= $value[$key].",";
        $cpt++;

    }
    return $data;
}
?>
<div class="row">
    <div class="col-6">
        <canvas id="myChart" width="200" height="200"></canvas>
    </div>
    <div class="col-6">
        <canvas id="myChart2" width="200" height="200"></canvas>
    </div>
</div>
<?php
$this->inlineScript()->captureStart();
?>
var ctx = document.getElementById('myChart');
var ctz = document.getElementById('myChart2');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: [<?= echoData($datas,'name',true) ?>],
        datasets: [{
            label: '# of abo',
            data: [<?= echoData($datas,'abo',false) ?>],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
var myChart2 = new Chart(ctz, {
    type: 'bar',
    data: {
        labels: [<?= echoData($datas,'name',true) ?>],
        datasets: [{
            label: '# of vue',
            data: [<?= echoData($datas,'vue',false) ?>],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
<?php
$this->inlineScript()->captureEnd();
