<?php

$title = 'domaines scientifique';
$this->headTitle($title);
?>
<div class="row m-1 justify-content-center">
    <div class="col">
        <table class="table table-hover table-dark">
            <thead>
                <tr>
                    <th scope="col">
                        Nom
                    </th>
                    <th scope="col">
                        Chaînes
                    </th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($domaines as $domaine): ?>
                <tr>
                    <td><?= $domaine->getNom(); ?></td>
                    <td><?= $this->formatData()->displayVulga($domaine->getVulga()); ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
