<?php

$title = 'Graphs';
$this->headTitle($title);

$this->headLink()->appendStylesheet($this->basePath('css/Chart.css'));
$this->headLink()->appendStylesheet($this->basePath('css/vulga.css'));
$this->headScript()->appendFile($this->basePath('js/Chart.bundle.min.js'));
$this->headScript()->appendFile($this->basePath('js/graph.js'));
$cpt= 0;
?>
<div class="mx-1">
    <span class="group">';
        <input type="radio" class="grand" name="graph" id="grand">
        <label for="grand">Grand</label><br>
        <input type="radio" class="moyen" name="graph" id="moyen" checked>
        <label for="moyen">Moyen</label>
        <input type="radio" class="petit" name="graph" id="petit">
        <label for="petit">Petit</label>
    </span>
</div>
<div class="row m-1 justify-content-center">
    <?php foreach($datas as $key => $data): ?>
        <div class="change col-6">
            <canvas id="myChart<?= $key ?>"></canvas>
        </div>
    <?php endforeach; ?>
</div>
<?php
$this->inlineScript()->captureStart();
foreach($datas as $key => $data):
?>
var ch<?= $key; ?> = document.getElementById('myChart<?= $key ?>');
var myChart<?= $key ?>= new Chart(ch<?= $key; ?>, {
    type: 'bar',
    data: {
        labels: [
        <?php foreach ($data as $value) echo "'".$this->escapeHtml($value['nom'])."',"; ?>
        ],
        datasets: [{
            label: '# de <?= $key; ?>',
            data: [
                <?php foreach ($data as $value) {
                    $mykey = array_keys($value);
                    echo addslashes($value[$mykey[1]]).",";
                } ?>
            ],
            fillColor: "rgba(220,220,220,0.5)",
            hoverBackgroundColor:"#FF1493",
            borderWidth: 1
        }]
    },
    options: {
        tooltips: {
            callbacks: {
                label: function(tooltipItem, data) {
                      return data.datasets[tooltipItem.datasetIndex].data[tooltipItem.index].toLocaleString('fr');
                 }
           }
        },
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
<?php
endforeach;
$this->inlineScript()->captureEnd();
?>
