<?php

$title = 'Graphs perso';
$this->headTitle($title);

$this->headLink()->appendStylesheet($this->basePath('css/Chart.css'));
$this->headLink()->appendStylesheet($this->basePath('css/bootstrap-select.min.css'));
$this->headLink()->appendStylesheet($this->basePath('css/vulga.css'));
$this->headScript()->appendFile($this->basePath('js/Chart.bundle.min.js'));
$this->headScript()->appendFile($this->basePath('js/bootstrap-select.min.js'));
$this->headScript()->appendFile($this->basePath('js/comp.js'));
$this->headScript()->appendFile($this->basePath('js/graph.js'));

$label = [
    'Nombre d\'abonnés moyen',
    'Nombre de vidéos moyen',
    'Nombre de vues moyen',
    'Nombre de Likes moyen',
    'Nombre de Dislikes moyen',
    'Temps de vidéo total moyen (en heures)',
    'Watch time moyen (en jours)',
    'Durée moyenne d\'une vidéo (en minutes)',
    'Nombre de Likes pour 1 Dislike',
    'Like moyen par vidéo',
    'Dislike moyen par vidéo',
    'Vue moyenne par vidéo'
];
if(!isset($valid)):
?>
<div class="row m-1 justify-content-center">
    <div class="col-1 mt-5 text-center">
        <a href="#" id="ajout">Ajouter un comparatif</a>
    </div>
</div>
<div class="row mt-1 justify-content-center" id="GraphForm">
</div>
<?php else: ?>
<div class="mx-1">
    <span class="group">';
        <input type="radio" class="grand" name="graph" id="grand">
        <label for="grand">Grand</label><br>
        <input type="radio" class="moyen" name="graph" id="moyen" checked>
        <label for="moyen">Moyen</label>
        <input type="radio" class="petit" name="graph" id="petit">
        <label for="petit">Petit</label>
    </span>
</div>
<div class="row m-1 justify-content-center">
    <div class="change col-6">
        <canvas id="chart0"></canvas>
    </div>
    <div class="change col-6">
        <canvas id="chart1"></canvas>
    </div>
    <div class="change col-6">
        <canvas id="chart2"></canvas>
    </div>
    <div class="change col-6">
        <canvas id="chart3"></canvas>
    </div>
    <div class="change col-6">
        <canvas id="chart4"></canvas>
    </div>
    <div class="change col-6">
        <canvas id="chart5"></canvas>
    </div>
    <div class="change col-6">
        <canvas id="chart6"></canvas>
    </div>
    <div class="change col-6">
        <canvas id="chart7"></canvas>
    </div>
    <div class="change col-6">
        <canvas id="chart8"></canvas>
    </div>
    <div class="change col-6">
        <canvas id="chart9"></canvas>
    </div>
    <div class="change col-6">
        <canvas id="chart10"></canvas>
    </div>
    <div class="change col-6">
        <canvas id="chart11"></canvas>
    </div>
</div>

<?php
$cpt = 0;
$dataGraph = [];
//convert Array
foreach ($graphData as $key => $value) {
    $graphData[$key] = array_values($value);
}

//generate random color
$elements = count($graphData);
$color1 = $color2 = "";
for($j = 0; $j < $elements; $j++) {
    $rColor = $this->formatData()->getRandomColor();
    $color1 .= "'rgba(".$rColor[0].",".$rColor[1].",".$rColor[2].",0.2)',";
    $color2 .= "'rgba(".$rColor[0].",".$rColor[1].",".$rColor[2].",1)',";
}

$this->inlineScript()->captureStart();

for($i = 0; $i < (count($graphData[0]) - 1); $i++):
?>
    var ch<?= $i; ?> = document.getElementById('chart<?= $i; ?>');
    var chart<?= $i; ?> = new Chart(ch<?= $i; ?>, {
        type: 'bar',
        data: {
            labels: [<?php foreach($graphData as $value) echo "'".str_replace([",","\n"],["","-"],$this->escapeHtml($value[0]))."',"; ?>],
            datasets: [{
                label: '<?= addslashes($label[$i]); ?>',
                data: [<?php foreach($graphData as $value) echo $value[$i+1].","; ?>],
                backgroundColor: [
                    <?= $color1; ?>
                ],
                borderColor: [
                    <?= $color2; ?>
                ],
                borderWidth: 1
            }]
        },
        options: {
            tooltips: {
                callbacks: {
                    label: function(tooltipItem, data) {
                          return data.datasets[tooltipItem.datasetIndex].data[tooltipItem.index].toLocaleString('fr');
                     }
               }
            },
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });
<?php
endfor;
$this->inlineScript()->captureEnd();
endif;
/*<pre><code><?php print_r($graphData); ?></code></pre>*/
?>
