<?php

$title = 'classement';
$this->headTitle($title);
?>
<div class="row m-1 justify-content-center">
    <h2>Aperçu rapide</h2>
</div>
<div class="row m-1 justify-content-center">
    <div class="col">
        <table class="table table-hover table-dark">
            <thead>
                <tr>
                    <th scope="col">
                        Chaîne Youtube
                    </th>
                    <th scope="col">
                        Abonnés
                    </th>
                    <th scope="col">
                        Vidéos
                    </th>
                    <th scope="col">
                        Vues
                    </th>
                    <th scope="col">
                        Like
                    </th>
                    <th scope="col">
                        Dislike
                    </th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($stats as $stat): ?>
                <tr>
                    <td><a target="_blank" rel="noopener noreferrer" href="<?= $stat->getMainstats()->last()->getLink(); ?>"><?= $stat->getNom(); ?></td>
                    <td><?= $this->formatData()->format($stat->getMainstats()->last()->getFollower()); ?></td>
                    <td><?= $this->formatData()->format($stat->getMainstats()->last()->getPosts()); ?></td>
                    <td><?= $this->formatData()->format($stat->getMainstats()->last()->getTotalVue()); ?></td>
                    <td><?= $this->formatData()->format($stat->getMainstats()->last()->getTotalLike()); ?></td>
                    <td><?= $this->formatData()->format($stat->getMainstats()->last()->getTotalDislike()); ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
