<?php

$title = 'classement';
$this->headTitle($title);
?>
<div class="row m-1 justify-content-center">
    <div class="col">
        <table class="table table-hover table-dark">
            <thead>
                <tr>
                    <th scope="col">
                        Chaine Youtube
                        <a href="<?= $this->url('science',['action' => 'index'],['query'=>['order' => 'nom','by' => 'asc']]);?>"><i class="fa fa-arrow-up" aria-hidden="true"></i></a>
                        <a href="<?= $this->url('science',['action' => 'index'],['query'=>['order' => 'nom','by' => 'desc']]);?>"><i class="fa fa-arrow-down" aria-hidden="true"></i></a>
                    </th>
                    <th scope="col">
                        Abonnés
                        <a href="<?= $this->url('science',['action' => 'index'],['query'=>['order' => 'abo','by' => 'asc']]);?>"><i class="fa fa-arrow-up" aria-hidden="true"></i></a>
                        <a href="<?= $this->url('science',['action' => 'index'],['query'=>['order' => 'abo','by' => 'desc']]);?>"><i class="fa fa-arrow-down" aria-hidden="true"></i></a>
                    </th>
                    <th scope="col">
                        Vidéos
                        <a href="<?= $this->url('science',['action' => 'index'],['query'=>['order' => 'vid','by' => 'asc']]);?>"><i class="fa fa-arrow-up" aria-hidden="true"></i></a>
                        <a href="<?= $this->url('science',['action' => 'index'],['query'=>['order' => 'vid','by' => 'desc']]);?>"><i class="fa fa-arrow-down" aria-hidden="true"></i></a>
                    </th>
                    <th scope="col">
                        Vues
                        <a href="<?= $this->url('science',['action' => 'index'],['query'=>['order' => 'vue','by' => 'asc']]);?>"><i class="fa fa-arrow-up" aria-hidden="true"></i></a>
                        <a href="<?= $this->url('science',['action' => 'index'],['query'=>['order' => 'vue','by' => 'desc']]);?>"><i class="fa fa-arrow-down" aria-hidden="true"></i></a>
                    </th>
                    <th scope="col">
                        Like
                        <a href="<?= $this->url('science',['action' => 'index'],['query'=>['order' => 'like','by' => 'asc']]);?>"><i class="fa fa-arrow-up" aria-hidden="true"></i></a>
                        <a href="<?= $this->url('science',['action' => 'index'],['query'=>['order' => 'like','by' => 'desc']]);?>"><i class="fa fa-arrow-down" aria-hidden="true"></i></a>
                    </th>
                    <th scope="col">
                        Dislike
                        <a href="<?= $this->url('science',['action' => 'index'],['query'=>['order' => 'dislike','by' => 'asc']]);?>"><i class="fa fa-arrow-up" aria-hidden="true"></i></a>
                        <a href="<?= $this->url('science',['action' => 'index'],['query'=>['order' => 'dislike','by' => 'desc']]);?>"><i class="fa fa-arrow-down" aria-hidden="true"></i></a>
                    </th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($stats as $stat): ?>
                <tr>
                    <td><a target="_blank" rel="noopener noreferrer" href="<?= $stat->getLink(); ?>"><?= $stat->getVulga()->getNom(); ?></td>
                    <td><?= $this->formatData()->format($stat->getFollower()); ?></td>
                    <td><?= $this->formatData()->format($stat->getPosts()); ?></td>
                    <td><?= $this->formatData()->format($stat->getTotalVue()); ?></td>
                    <td><?= $this->formatData()->format($stat->getTotalLike()); ?></td>
                    <td><?= $this->formatData()->format($stat->getTotalDislike()); ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
