<?php

$title = 'stats globales';
$this->headTitle($title);

$totalAbo = 0;
$totalVideo = 0;
$totalVue = 0;
$totaVue_v = 0;
$totalLike = 0;
$totalDislike = 0;
$totalLike_v = 0;
$totalDislike_v = 0;
$totalDuration = 0;
$totalDuration_v = 0;
$totalWatch = 0;

$cpt = 0;

foreach ($datas as $data) {
    $totalAbo += $data['abo'];
    $totalVideo += $data['vid'];
    $totalVue += $data['vue'];
    $totalLike += $data['like'];
    $totalDislike += $data['dislike'];
    $totalDuration += $data['minutes'];
    $totalDuration_v += $data['min_v'];
    $totalWatch += $data['watch'];
    $cpt++;
}
?>
<div class="row mt-5 justify-content-center">
    <div class="col-2">
        <p>
            Il y a <?= $cpt ?> chaînes enregistrées. <br>
            Chaque chaîne à en moyenne :
            <ul>
                <li> <?= $this->formatData()->format($totalAbo/$cpt,2); ?> Abonnés </li>
                <li> <?= $this->formatData()->format($totalVideo/$cpt,2); ?> Vidéos </li>
                <li> <?= $this->formatData()->format($totalVue/$cpt,2); ?> Vues </li>
                <li> <?= $this->formatData()->format($totalLike/$cpt,2); ?> Like </li>
                <li> <?= $this->formatData()->format($totalDislike/$cpt,2); ?> Dislike </li>
                <li> <?= $this->formatData()->timeConverter($totalDuration/$cpt); ?> de vidéos </li>
                <li> <?= $this->formatData()->timeConverter($totalWatch/$cpt); ?> de watch time </li>
            </ul>
        </p>
    </div>
    <div class="col-2">
        <p>
            Il y a en tout :
            <ul>
                <li> <?= $this->formatData()->format($totalVideo); ?> Vidéos </li>
                <li> <?= $this->formatData()->format($totalVue); ?> Vues </li>
                <li> <?= $this->formatData()->format($totalLike); ?> Like </li>
                <li> <?= $this->formatData()->format($totalDislike); ?> Dislike </li>
                <li> <?= $this->formatData()->timeConverter($totalDuration); ?> de vidéos </li>
                <li> <?= $this->formatData()->timeConverter($totalWatch); ?> de watch time </li>
            </ul>
        </p>
    </div>
</div>
